apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cd-album-list
  name: cd-album-list
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cd-album-list
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cd-album-list
    spec:
      containers:
        - name: django
          image: s1f102102379/cd-album-list:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /1
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
      restartPolicy: Always